image: chilio/laravel-dusk-ci:stable

before_script:
  - php -v

cache:
  paths:
    - vendor
    - storage

stages:
  - test
  - command

test:
  stage: test
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - vendor/bin/phpunit
  except:
    - schedules

command:
  stage: command
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php arty discord:test --body='test@GitLab CI'
  only:
    - schedules
