name: composer update

on:
  schedule:
    - cron: '0 4 * * *' #UTC

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@v1
    secrets:
      token: ${{ secrets.ACTION_TOKEN }}
    with:
      php: 8.2
      extensions: mbstring
      git-name: kawax
      git-email: 1502086+kawax@users.noreply.github.com
